# Generated by Django 4.2.2 on 2023-06-07 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-published_at']},
        ),
        migrations.AlterModelTable(
            name='category',
            table='category_table',
        ),
        migrations.AlterModelTable(
            name='job',
            table='jobs_table',
        ),
    ]
