# Generated by Django 4.2.2 on 2023-06-07 09:52

from django.db import migrations, models
import jobsApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsApp', '0002_alter_job_options_alter_category_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=jobsApp.models.image_upload),
        ),
    ]
